#!/usr/bin/env python3
"""Content rules, asserted against the artifacts and skills on disk.

Dependency-free. Run directly:  python3 tests/test_prohibitions.py

Every rule here is something a context-free session does by default because it
is locally the obvious move. See CLAUDE.md -> Prohibitions.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FAILURES = []

# PRD 5.1 — the seven required frontmatter fields.
REQUIRED_FIELDS = ["artifact", "feature", "version", "status",
                   "generated-by", "upstream", "downstream"]

# PRD 5.2 — the complete set of artifact: values in use.
ARTIFACT_VALUES = {
    "BRIEF", "PRD", "USM", "USL", "USD", "UAT",
    "WF", "COMP", "INT",
    "STRATEGY", "OST", "MARKET-RESEARCH", "NSM", "GROWTH-LOOP", "GTM-PLAN",
}

# PRD 5.3
STATUS_VALUES = {"draft", "review", "approved"}

# generated-by values with no corresponding skill. Declared, not silently allowed —
# each is tracked in docs/STATE.md under Known broken.
GENERATED_BY_EXCEPTIONS = {
    "design-interactions",   # stage 3 is manual; no skill wraps it
    "pm-to-po-handoff",      # never existed as a skill
}


def fail(check, msg):
    FAILURES.append(f"{check}: {msg}")


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def skill_names():
    d = os.path.join(ROOT, "skills")
    return {n for n in os.listdir(d)
            if os.path.isfile(os.path.join(d, n, "SKILL.md"))}


def artifact_files():
    out = []
    for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, "features")):
        for fn in filenames:
            if fn.endswith(".md"):
                out.append(os.path.join(dirpath, fn))
    return sorted(out)


def frontmatter(text):
    """Return the YAML frontmatter block as a dict of raw strings, or None."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    block, out = text[3:end], {}
    for line in block.splitlines():
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$", line)
        if m:
            out[m.group(1)] = m.group(2).strip()
    return out


def rel(path):
    return os.path.relpath(path, ROOT)


# ---------------------------------------------------------------- checks

def check_artifact_frontmatter():
    """PRD 5.1 — all seven fields, on every artifact."""
    for path in artifact_files():
        fm = frontmatter(read(path))
        if fm is None:
            fail("frontmatter", f"{rel(path)} has no YAML frontmatter")
            continue
        for field in REQUIRED_FIELDS:
            if field not in fm:
                fail("frontmatter", f"{rel(path)} is missing '{field}:'")
            elif not fm[field]:
                fail("frontmatter", f"{rel(path)} has an empty '{field}:'")


def check_artifact_values():
    """PRD 5.2 — artifact: must be one of the documented values."""
    for path in artifact_files():
        fm = frontmatter(read(path)) or {}
        value = fm.get("artifact")
        if value and value not in ARTIFACT_VALUES:
            fail("artifact-value",
                 f"{rel(path)} has 'artifact: {value}', which is not in PRD 5.2")


def check_status_values():
    """PRD 5.3 — status must be draft | review | approved."""
    for path in artifact_files():
        fm = frontmatter(read(path)) or {}
        value = fm.get("status")
        if value and value not in STATUS_VALUES:
            fail("status", f"{rel(path)} has 'status: {value}'; expected one of {sorted(STATUS_VALUES)}")


def check_generated_by_names_a_skill():
    """generated-by must name a real skill, or a declared exception."""
    skills = skill_names()
    for path in artifact_files():
        fm = frontmatter(read(path)) or {}
        value = fm.get("generated-by")
        if value and value not in skills and value not in GENERATED_BY_EXCEPTIONS:
            fail("generated-by",
                 f"{rel(path)} was generated by '{value}', which is not a skill")


def check_feature_matches_folder():
    """PRD 5.1 — feature: must mirror the folder name exactly, spaces and all."""
    features_root = os.path.join(ROOT, "features")
    for path in artifact_files():
        folder = os.path.relpath(path, features_root).split(os.sep)[0]
        fm = frontmatter(read(path)) or {}
        value = fm.get("feature")
        if value and value != folder:
            fail("feature-name",
                 f"{rel(path)} says 'feature: {value}' but lives in '{folder}'")


# PRD 3.2 gives wireframes and interactions the same rule: sections in one shared
# file, never one file per ID. Any WF-*.md or INT-*.md under a design/ folder is a defect.
PER_ID_FILE = re.compile(r"^(WF|INT)-[A-Za-z0-9-]+\.md$")


def check_no_per_id_design_files():
    """PRD 3.2 / decision 0001 — wireframes and interactions live in one file each."""
    for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, "features")):
        if os.path.basename(dirpath) != "design":
            continue
        for fn in filenames:
            if PER_ID_FILE.match(fn):
                kind = "wireframes.md" if fn.startswith("WF") else "interactions.md"
                fail("design-files",
                     f"{rel(os.path.join(dirpath, fn))} — belongs in design/{kind} (PRD 3.2)")


def check_skill_frontmatter():
    """ARCHITECTURE 3.2 — description: is the trigger text; both fields are required."""
    for name in sorted(skill_names()):
        path = os.path.join(ROOT, "skills", name, "SKILL.md")
        fm = frontmatter(read(path))
        if fm is None:
            fail("skill-frontmatter", f"skills/{name}/SKILL.md has no frontmatter")
            continue
        for field in ("name", "description"):
            if not fm.get(field):
                fail("skill-frontmatter", f"skills/{name}/SKILL.md has no '{field}:'")
        if fm.get("name") and fm["name"] != name:
            fail("skill-frontmatter",
                 f"skills/{name}/SKILL.md declares name '{fm['name']}'")


# ---------------------------------------------------------------- self-probe

def self_probe():
    """Verify the detectors bite. A vacuous test is worse than no test."""
    good = "---\nartifact: PRD\nstatus: draft\n---\nbody"
    bad_none = "no frontmatter here"
    if frontmatter(good) is None:
        fail("self-probe", "frontmatter() failed to parse a valid block")
    if frontmatter(good).get("artifact") != "PRD":
        fail("self-probe", "frontmatter() parsed the wrong value")
    if frontmatter(bad_none) is not None:
        fail("self-probe", "frontmatter() accepted a file with no frontmatter")
    for bad in ("WF-001.md", "WF-XXX.md", "WF-AUTH-001.md", "INT-001.md", "INT-XXX.md"):
        if not PER_ID_FILE.match(bad):
            fail("self-probe", f"design-file detector does not match known-bad {bad!r}")
    for good in ("wireframes.md", "interactions.md", "COMP-001.md"):
        if PER_ID_FILE.match(good):
            fail("self-probe", f"design-file detector fires on correct filename {good!r}")
    empty = "---\nartifact: PRD\nfeature:\n---\nbody"
    if frontmatter(empty).get("feature") != "":
        fail("self-probe", "frontmatter() does not surface an empty value as empty")
    if not skill_names():
        fail("self-probe", "skill_names() found nothing — the detector is blind")
    if not artifact_files():
        fail("self-probe", "artifact_files() found nothing — the detector is blind")
    if "PM-STRATEGY" in ARTIFACT_VALUES:
        fail("self-probe", "PM-STRATEGY must not be an accepted artifact value (PRD 5.2)")


def main():
    self_probe()
    for name, fn in sorted(globals().items()):
        if name.startswith("check_") and callable(fn):
            fn()
    if FAILURES:
        print(f"FAIL — {len(FAILURES)} problem(s):\n")
        for f in FAILURES:
            print("  " + f)
        return 1
    n_art = len(artifact_files())
    print(f"ok — {n_art} artifacts and {len(skill_names())} skills satisfy the content rules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
